import type { Metadata } from 'next'
import { outfit } from './ui/fonts'
import './globals.css'
import Navbar from './ui/components/Navbar'
import {getAuthenticatedAppForUser} from "@/firebase/firebase";



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
const {currentUser} = await getAuthenticatedAppForUser()
  return (
    <html lang="en">
      <body
        className={`${outfit.className} bg-entertainment-dark-blue grid grid-cols-1 lg:grid-cols-2`}
      >
        {/* @ts-ignore */}
        <Navbar initialUser={currentUser?.toJSON()} />
        {children}
      </body>
    </html>
  );
}
